_AgathaBeforeBattleText::
	text "I am AGATHA of"
	line "the ELITE FOUR!"
	para "So... OAK finally"
	line "sent his little"
	cont "scientist."
	para "Do you really"
	line "think that his"
	cont "research was"
	cont "paid for by"
	cont "grants alone?"
	para "In those days,"
	line "there wasn't much"
	cont "money for #MON"
	cont "science."
	para "The only people"
	line "willing to fund"
	cont "ambitious work..."
	cont "Asked no"
	cont "questions."
	para "Some of those"
	line "people became"
	cont "TEAM ROCKET."
	para "OAK will tell you"
	line "he never joined"
	cont "them."
	para "Perhaps."
	para "But money always"
	line "leaves finger-"
	cont "prints."
	para "Tell me,"
	line "<PLAYER>..."
	para "Will you inherit"
	line "his discoveries?"
	para "Or his mistakes?"
	done
_AgathaEndBattleText::
	text "Hmph."
	para "Perhaps OAK chose"
	line "the right students"
	cont "after all."
	prompt
_AgathaAfterBattleText::
	text "Listen carefully."
	para "Your teacher built"
	line "a better future."
	para "But he did not"
	line "build it with"
	cont "clean hands."
	para "Ask him what"
	line "became of the"
	cont "people who first"
	cont "funded his work."
	para "Then decide what"
	line "kind of scientist"
	cont "you'll become."
	done
_AgathasRoomAgathaDontRunAwayText::
	text "Someone's voice:"
	line "Don't run away!"
	done
