_BillsHouseBillImNotAPokemonText::
	text "Finally!"
	para "Another"
	line "scientist!"
	para "I'm BILL."
	para "No, I'm not a"
	line "#MON."
	para "Though I admit"
	line "the evidence is"
	cont "against me."
	para "I'm not joshing"
	line "you, I screwed up"
	cont "an experiment and"
	cont "got fused with"
	cont "my #MON!"
	para "So, how about it?"
	line "Help me out here!"
	para "Please..."
	line "tell me you know"
	cont "how to use a PC!"
	done
_BillsHouseBillUseSeparationSystemText::
	text "When I'm in the"
	line "TELEPORTER, go to"
	cont "my PC and run the"
	cont "Cell Separation"
	cont "System!"
	para "Don't worry,"
	line "there's a"
	cont "README"
	cont "somewhere."
	done
_BillsHouseBillNoYouGottaHelpText::
	text "No!? You're really"
	line "going to leave"
	cont "a fellow"
	cont "scientist like"
	cont "this?"
	para "Please? I'm"
	line "begging you!"
	prompt
_BillsHouseBillThankYouText::
	text "BILL: Yeehaw!"
	para "... Wait, where's"
	line "my #MON?"
	para "Oh, no..."
	line "It must have"
	cont "vaporized when"
	cont "the Cell Separ-"
	cont "ation System"
	cont "restored me to"
	cont "my old state."
	para "Alas."
	para "I knew OAK picked"
	line "the right person"
	cont "for the job."
	para "Most trainers"
	line "would've run"
	cont "away screaming!"
	para "I owe you."
	para "Here, maybe"
	line "this'll do."
	prompt
_SSTicketReceivedText::
	text "<PLAYER> received"
	line "an @"
	text_ram wStringBuffer
	text "!@"
	text_end
_SSTicketNoRoomText::
	text "You've got too"
	line "much stuff, bud!"
	done
_BillsHouseBillWhyDontYouGoInsteadOfMeText::
	text "That cruise ship,"
	line "S.S.ANNE, is"
	cont "docked in"
	cont "VERMILION CITY."
	cont "Its passengers"
	cont "are all trainers!"
	para "They invited me"
	line "to their party,"
	cont "but I can't stand"
	cont "fancy do's. I'd"
	cont "rather stay here"
	cont "to continue with"
	cont "my research! Why"
	cont "don't you go"
	cont "instead of me?"
	done
_BillsHouseBillCheckOutMyRarePokemonText::
	text "BILL: Come back,"
	line "sometime."
	para "I'd love another"
	line "scientist's"
	cont "opinion on my"
	cont "#MON research."
	done
