_ChampionsRoomRivalIntroText::
	text "<RIVAL>: It's you."
	line "After all this"
	cont "time."
	para "I see now that"
	line "you're simply"
	cont "obsessed with"
	cont "proving me"
	cont "wrong..."
	para "AGATHA thinks I"
	line "lost my way."
	para "OAK thinks power"
	line "should come from"
	cont "friendship."
	para "They're both"
	line "living in the"
	cont "past."
	para "The strongest"
	line "trainer is the"
	cont "one who uses"
	cont "every advantage."
	done
_RivalDefeatedText::
	text ""
	line "Impossible..."
	para "I did everything"
	line "right."
	para "I took every"
	line "advantage."
	para "Every shortcut."
	para "Every opportunity."
	para "...And it still"
	line "wasn't enough?"
	prompt
_RivalVictoryText::
	text "Hahaha!"
	line "I won, I won!"
	para "I'm too good for"
	line "you, <PLAYER>!"
	para "You did well to"
	line "even reach me,"
	cont "<RIVAL>, the"
	cont "#MON genius!"
	para "Nice try, loser!"
	line "Hahaha!"
	prompt
_ChampionsRoomRivalAfterBattleText::
	text "I still don't"
	line "understand."
	para "By every measure,"
	line "I should have"
	cont "won."
	para "Maybe there's"
	line "something OAK"
	cont "never taught me."
	para "You're the"
	line "CHAMPION."
	para "...For now."
	done
_ChampionsRoomOakText::
	text "OAK: <RIVAL>!"
	done
_ChampionsRoomOakCongratulatesPlayerText::
	text "OAK: You believed"
	line "every advantage"
	cont "made you stronger"
	cont "..."
	para "But you stopped"
	line "asking why your"
	cont "#MON followed"
	cont "you at all."
	para "And look at the"
	line "consequences,"
	cont "your PORYGON"
	cont "destroyed."
	para "Power can be"
	line "taken."
	para "Trust cannot."
	para "That is why you"
	line "lost."
	done
_ChampionsRoomOakDisappointedWithRivalText::
	text "OAK: <PLAYER>! I'm"
	line "impressed with"
	cont "you for once!"
	para "I came when I"
	line "heard <RIVAL>"
	cont "had beat the"
	cont "ELITE FOUR!"
	para "But, when I got"
	line "here, he had"
	cont "already lost!"
	para "<PLAYER>! Do you"
	line "understand why"
	cont "you won?"
	para "You remembered"
	line "to treat your"
	cont "#MON with"
	cont "trust and love!"
	para "Without them, you"
	line "will have never"
	cont "become CHAMPION!"
	done
_ChampionsRoomOakComeWithMeText::
	text "OAK: <PLAYER>!"
	para "Today you became"
	line "CHAMPION."
	para "But your journey"
	line "isn't over yet."
	para "Come with me."
	para "There's something"
	line "I'd like the whole"
	cont "LEAGUE to see."
	done
