_FuchsiaMartMiddleAgedManText::
	text "Excuse me, young"
	line "man, do you work"
	cont "here?"
	para "Do you have a"
	line "SAFARI ZONE flag?"
	para "What about cards"
	line "or calendars?"
	done
_FuchsiaMartCooltrainerFText::
	text "If you're travel-"
	line "ing by sea, be"
	cont "sure to stock"
	cont "up on # DOLLS."
	para "# DOLLS will"
	line "make it easier"
	cont "to escape battles"
	cont "with #MON"
	cont "that are much"
	cont "stronger than"
	cont "your own!"
	para "There are some"
	line "really wicked"
	cont "#MON out at"
	cont "sea, but they"
	cont "may prove too"
	cont "powerful for"
	cont "you!"
	done
