_HallOfFameOakText::
	text "OAK: Congratul-"
	line "ations, <PLAYER>."
	para "Many trainers"
	line "dream of standing"
	cont "here."
	para "Few ever do."
	para "You found more"
	line "than victory on"
	cont "your journey."
	para "Some discoveries"
	line "brought hope."
	para "Others carried"
	line "a heavy price."
	para "Still..."
	para "You never stopped"
	line "moving forward."
	para "Come."
	para "The HALL OF FAME"
	line "is waiting."
	done
