_LancesRoomLanceBeforeBattleText::
	text "So."
	para "You're <PLAYER>."
	para "I've heard of your"
	line "journey."
	para "You sought out"
	line "#MON few"
	cont "trainers have"
	cont "ever seen."
	para "But knowledge"
	line "alone won't carry"
	cont "you any farther."
	para "The ELITE FOUR"
	line "exist to protect"
	cont "the LEAGUE from"
	cont "the unworthy."
	para "Show me you've"
	line "earned the right"
	cont "to go on!"
	para "Come!"
	done
_LancesRoomLanceEndBattleText::
	text "Excellent"
	line "..."
	para "You've proven"
	line "yourself."
	prompt
_LancesRoomLanceAfterBattleText::
	text "You have the heart"
	line "of a CHAMPION."
	para "Under ordinary"
	line "circumstances..."
	para "...this is where"
	line "I would welcome"
	cont "you as the new"
	cont "CHAMPION."
	para "But something has"
	line "changed."
	para "Another trainer"
	line "defeated us"
	cont "before you"
	cont "arrived."
	para "Your rival..."
	para "He's waiting in"
	line "the CHAMPION's"
	cont "ROOM."
	para "Go."
	para "Finish what both"
	line "of us started.@"
	text_end
