_PewterGymBrockPreBattleText::
	text "Hey! Welcome to"
	line "PEWTER GYM."
	para "I'm BROCK, the"
	line "GYM LEADER here."
	para "I cannot express"
	line "how surprised I"
	cont "was upon learning"
	cont "that PROF.OAK's"
	cont "AIDEs are taking"
	cont "on the #MON"
	cont "GYM CHALLENGE."
	para "But, I see you"
	line "have #MON"
	cont "with you. That's"
	cont "surely a sign"
	cont "you've trained"
	cont "with them."
	para "I raise rock-hard"
	line "#MON! And when"
	cont "I say rock-hard,"
	cont "I really mean it!"
	para "Think you've got"
	line "what it takes?"
	para "Then show me what"
	line "you and your"
	cont "#MON can do!"
	done
_PewterGymRematchPreBattleText::
	text "You've come far"
	line "since we met."
	para "Back then, I"
	line "saw potential."
	para "Now I see a"
	line "true trainer."
	para "I've trained"
	line "hard as well."
	para "Let's see how"
	line "much we've"
	cont "grown!"
	done
_PewterGymRematchAcceptedText::
	text "Excellent!"
	para "Show me the"
	line "strength that"
	cont "made you"
	cont "CHAMPION!"
	done
_PewterGymRematchRefusedText::
	text "...I'll be here."
	para "Come back when"
	line "you're ready."
	done
_PewterGymRematchDefeatedText::
	text ""
	line "Outstanding."
	line "You've become"
	cont "a true master."
	prompt
_PewterGymRematchPostBattleText::
	text "A fine battle."
	para "You've earned"
	line "your title."
	para "I'll keep"
	line "training, too."
	para "Next time,"
	line "I'll be ready."
	para "New challenges"
	line "await."
	done
