	DEF NUM_PLAYER_NAMES EQU 3
	IF DEF(_RED)
	DEF PLAYERNAME1 EQUS "HITACHI"
	DEF PLAYERNAME2 EQUS "BLAKE"
	DEF PLAYERNAME3 EQUS "ISAAC"
	DEF RIVALNAME1 EQUS "NINTEN"
	DEF RIVALNAME2 EQUS "MELVIN"
	DEF RIVALNAME3 EQUS "DEXTER"
	ENDC
	IF DEF(_BLUE)
	DEF PLAYERNAME1 EQUS "NINTEN"
	DEF PLAYERNAME2 EQUS "MELVIN"
	DEF PLAYERNAME3 EQUS "DEXTER"
	DEF RIVALNAME1 EQUS "HITACHI"
	DEF RIVALNAME2 EQUS "BLAKE"
	DEF RIVALNAME3 EQUS "ISAAC"
	ENDC
